apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - pvc-config.yaml
  - service.yaml
images:
  - name: sonarr-image
    newName: ghcr.io/linuxserver/sonarr
    newTag: 4.0.9@sha256:db80ed8022dd15143644752a57db0553e48e23e3da54bdb9833d28ff89206a3c
