apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - pvc-config.yaml
  - service.yaml
images:
  - name: prowlarr-image
    newName: ghcr.io/linuxserver/prowlarr
    newTag: 1.24.3@sha256:a6fc8ab9ff34d82327d29f8b5bfb7a672c0e54a274e5e5b023db01c335d05dfd
