apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - pvc-config.yaml
  - service.yaml
images:
  - name: prowlarr-image
    newName: ghcr.io/linuxserver/prowlarr
    newTag: 1.25.4@sha256:1e2fffd859ecd260e4aae4798cf5be75938cd602161d21b1d58122afb397c864
