apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: plex-media-server
    releaseName: plex
    repo: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    valuesFile: values.yaml
    version: 0.4.0
resources:
  - csi-pv.yaml
  - pvc-data.yaml
namespace: plex
patches:
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: plex-plex-media-server-ingress
      spec:
        tls: null
    target:
      kind: Ingress
      name: plex-plex-media-server-ingress
  - patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: plex-plex-media-server
      spec:
        template:
          spec:
            hostNetwork: true
labels:
  - includeSelectors: true
    pairs:
      app: plex
