---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 264Gi
  volumeName: pv-smb-media
  storageClassName: smb
