apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - pvc-config.yaml
  - service.yaml
images:
  - name: tranmission-image
    newName: ghcr.io/linuxserver/transmission
    newTag: 4.0.6@sha256:9c524c93fa81488612975d1c3a4b73453f7b89074334efad1261699c5cb7de7f
