apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - csi-pv.yaml
  - deployment.yaml
  - ingress.yaml
  - pvc-data.yaml
  - service.yaml
images:
  - name: tranmission-image
    newName: ghcr.io/linuxserver/transmission
    newTag: latest
