name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * */1"
concurrency: renovate
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@80eaf969abf68ad62aa94d9ab392421b31621634 # v40.3.4
        env:
          RENOVATE_REPOSITORIES: "${{ github.repository }}"
          RENOVATE_ONBOARDING: "true"
          RENOVATE_USERNAME: "mallie-su"
          RENOVATE_GIT_AUTHOR: "Renovate <allie.matthieu@gmail.com>"
          GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          LOG_LEVEL: 'debug'
        with:
          configurationFile: .github/renovate.js
          token: ${{ secrets.RENOVATE_TOKEN }}
