name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * */1"
concurrency: renovate
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v40.2.6
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
