name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * */1"
concurrency: renovate
jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@e1db501385ddcccbaae6fb9c06befae04f379f23 # v40.2.10
        env:
          RENOVATE_REPOSITORIES: "${{ github.repository }}"
          RENOVATE_ONBOARDING: "true"
          RENOVATE_USERNAME: "Renovate[bot]"
          RENOVATE_GIT_AUTHOR: "Renovate <allie.matthieu@gmail.com>"
          LOG_LEVEL: 'debug'
        with:
          configurationFile: .github/renovate.js
          token: ${{ secrets.RENOVATE_TOKEN }}
