name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * */1"
concurrency: renovate
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v40.2.6
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: "false"
          RENOVATE_USERNAME: "Renovate[bot]"
          RENOVATE_GIT_AUTHOR: "renovate@sp4rck.ovh"
          RENOVATE_PLATFORM_COMMIT: "true"
          LOG_LEVEL: 'info'
        with:
          configurationFile: .github/renovate.js
          token: ${{ secrets.RENOVATE_TOKEN }}
